name: parcelflow
version: 1.0.0
config-version: 2
profile: parcelflow
model-paths: ["models"]
models:
parcelflow:
staging:
+schema: staging
+materialized: view
marts:
+schema: marts
+materialized: view